name: ISSUE TEMPLATE
description: File a ISSUE TEMPLATE
title: "✨ Feat: "

body:
  - type: markdown
    attributes:
      value: |
        ✨ Feat : 새로운 기능 추가 및 기존 기능 요구사항에 맞춰 수정
        🐛 Fix : 기능에 대한 버그 수정
        ♻️ Refactor : 코드 리팩토링
        💄 Design : CSS 및 디자인 수정
        📝 Doc : 문서 수정
        🚨 Hotfix : 급한 수정
        📦 Chore : 그 외 기타 수정

  - type: textarea
    id: title
    attributes:
      label: ✨ 작업 내용
      description: 해야할 작업에 대해서 간단하게 적어주세요
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: ⚙ 상세한 작업 내용
      description: 상세한 작업 내용을 적어주세요
      value: "- [ ] :

        - [ ] :

        - [ ] : "
    validations:
      required: true
